/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, } from 'react'
import { useGLTF } from '@react-three/drei'


const Escena = (props) => {



  const modelPath = import.meta.env.PROD 
    ? '/CVweb/models/simpleDuck.glb'  // Ruta para producción (GitHub Pages)
    : './models/simpleDuck.glb';       // Ruta para desarrollo (localhost)

  // ▶ 2. Carga el modelo con la ruta condicional
  const { nodes, materials } = useGLTF(modelPath);
  return (
    <group {...props} dispose={null} position={[0, -1, 0]} scale={[0.5, 0.5, 0.5]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_1.geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_2.geometry}
        material={materials['Material.002']}
      />
    </group>
  )
}

useGLTF.preload('./models/simpleDuck.glb')

export default Escena;
